name: rust-qldpc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rust
  - git
  - maturin
  - numpy
  - scipy
  - matplotlib
  - numba
  - pandas
  - tqdm
  - pip
  - pip:
      - quits
      - stim
      - ldpc
      - coordinator @ git+https://github.com/antsouchlos/coordinator.git
