import numpy as np
from numpy.typing import NDArray
from scipy.sparse import csr_matrix

class VanillaMinSumDecoder:
    def __init__(self, H: csr_matrix, priors: NDArray[np.float64], max_iter: int) -> None: ...
    def decode(self, syndrome: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_batch(self, syndromes: NDArray[np.uint8]) -> NDArray[np.uint8]: ...

class VanillaSpaDecoder:
    def __init__(self, H: csr_matrix, priors: NDArray[np.float64], max_iter: int) -> None: ...
    def decode(self, syndrome: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_batch(self, syndromes: NDArray[np.uint8]) -> NDArray[np.uint8]: ...

class SlidingWindowMinSumDecoder:
    def __init__(self, H: csr_matrix, m: int, num_rounds: int, W: int, F: int, priors: NDArray[np.float64], max_iter: int, warm_start: bool) -> None: ...
    def decode(self, syndrome: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_batch(self, syndromes: NDArray[np.uint8]) -> NDArray[np.uint8]: ...

class SlidingWindowSpaDecoder:
    def __init__(self, H: csr_matrix, m: int, num_rounds: int, W: int, F: int, priors: NDArray[np.float64], max_iter: int, warm_start: bool) -> None: ...
    def decode(self, syndrome: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_batch(self, syndromes: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
